### ISSUE TITLE
Close varioius pickers on ESC

### ISSUE THREAD

**Issue by kchibisov** [chrisduerr/sketch#11]

**Comment by chrisduerr** [comment]
This is kind of a difficult one, since `ESC` is also the start for escape sequences. I've considered a few different ways on how this could be best done, but I'm not sure about any of those solutions.

Other libraries seem to handle this by timeouts or detecting ESC based on writes (so checking if the PTY is blocking between reads). But I don't think there's anything that just works reliably without any problems.
