### ISSUE TITLE
Ability to save drawing

### ISSUE THREAD

**Issue by kchibisov** [chrisduerr/sketch#8]
It'll be nice to have an ability to save drawing somehow, so it could be easily shared without making a screenshot. However I'm not sure what format could be used for them, maybe something like HTML or txt file with escapes like recordings in alacritty? With html one could post a file via paste bin service, like paste.rs and it'll be nicely rendered, however it'll be more efficient than png.

Though, if you can save drawing you should have an ability to continue drawing, and here escape sequence format is preferable, I'd say.

Though, one issue with escape sequence is that it should be restored on a size that was used when drawing, so the size should be saved somehow.

**Comment by chrisduerr** [comment]
One of the purposes of printing the drawing once you leave the application is as a sort of way to persist it. It is however true that you cannot just take that and copy/paste it somewhere because it will lose all color.

It would be nice to be able to just pipe it into something else, but of course you need stdout to actually draw stuff.

A terminal supporting copy with escape sequences would probably make this quite trivial, which is something that I think makes sense. But generally chances are the best solution would be to at least offer output into a file after execution is finished.

This output file could be either set by CLI flag, or just using the existing dialog code to prompt for it on exit.

**Comment by chrisduerr** [comment]
> Though, one issue with escape sequence is that it should be restored on a size that was used when drawing, so the size should be saved somehow.

This shouldn't be necessary since linewraps are ignored. So the drawing will look just fine as long as your window is at least as big as the original canvas. If it's smaller, there's no reasonable way to handle it anyways.
